"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { cartApi } from "../api/cart.api";
import { accountApi } from "@/features/account/api/account.api";
import { AddressForm } from "@/features/account/components/addresses";
import { useSessionStore } from "@/features/auth/store/session.store";
import { Button, Notice, Page, LoginRequired } from "@/components/ui";
export function CartView() {
  const user = useSessionStore(s => s.user); const cache = useQueryClient(); const router = useRouter();
  const [addressId, setAddressId] = useState(""); const [attempt, setAttempt] = useState<{ key: string; address: string } | null>(null);
  const cart = useQuery({ queryKey: ["cart", user?.id], queryFn: cartApi.list, enabled: !!user });
  const addresses = useQuery({ queryKey: ["addresses", user?.id], queryFn: accountApi.addresses, enabled: !!user });
  const update = useMutation({ mutationFn: ({ id, quantity }: { id: string; quantity: number }) => quantity === 0 ? cartApi.removeItem(id) : cartApi.setItem(id, quantity), onSettled: () => cache.invalidateQueries({ queryKey: ["cart"] }) });
  const checkout = useMutation({ mutationFn: ({ key, address }: { key: string; address: string }) => accountApi.checkout(address, key), onSuccess: order => { setAttempt(null); void cache.invalidateQueries({ queryKey: ["cart"] }); void cache.invalidateQueries({ queryKey: ["orders"] }); router.push(`/orders/${order.id}`); } });
  return <Page title="Giỏ hàng của bạn">{!user ? <LoginRequired/> : <div className="grid gap-8 lg:grid-cols-[1.5fr_1fr]"><section>{cart.isPending && <Notice>Đang tải giỏ hàng…</Notice>}{cart.error && <Notice error>{cart.error.message}</Notice>}{cart.data?.length === 0 && <Notice>Giỏ hàng trống. <Link href="/products" className="underline">Mua sắm ngay</Link></Notice>}{cart.data?.map(item => <div key={item.id} className="mb-4 rounded-sm border border-zinc-200 bg-white p-5"><p className="mb-3 break-all text-sm font-medium">Phiên bản {item.VariantID}</p><div className="flex items-center gap-3"><Button aria-label="Giảm số lượng" disabled={!!attempt || update.isPending || item.Quantity <= 1} onClick={() => update.mutate({ id: item.VariantID, quantity: item.Quantity - 1 })}>−</Button><span>{item.Quantity}</span><Button aria-label="Tăng số lượng" disabled={!!attempt || update.isPending || item.Quantity >= 10000} onClick={() => update.mutate({ id: item.VariantID, quantity: item.Quantity + 1 })}>+</Button><button disabled={!!attempt || update.isPending} className="ml-auto text-sm text-red-600" onClick={() => update.mutate({ id: item.VariantID, quantity: 0 })}>Xóa</button></div></div>)}{update.error && <Notice error>{update.error.message}</Notice>}<Notice>Thông tin tên và giá hiện chưa có trong giỏ hàng. Tổng tiền chính thức được xác nhận trên đơn hàng sau khi đặt.</Notice><AddressForm/></section><aside className="h-fit rounded-sm bg-zinc-50 p-6"><h2 className="mb-5 text-xl font-semibold">Đặt hàng</h2><label className="text-sm">Địa chỉ nhận hàng<select className="mt-2" disabled={!!attempt} value={addressId} onChange={e => setAddressId(e.target.value)}><option value="">Chọn địa chỉ</option>{addresses.data?.map(a => <option key={a.id} value={a.id}>{a.RecipientName} · {a.AddressLine}, {a.Province}</option>)}</select></label>{addresses.error && <Notice error>{addresses.error.message}</Notice>}<p className="my-5 text-sm text-zinc-600">Thanh toán khi nhận hàng (COD). Miễn phí vận chuyển. Đặt toàn bộ giỏ hàng hiện tại.</p><Button className="w-full" disabled={!addressId || !cart.data?.length || checkout.isPending || update.isPending} onClick={() => { const next = attempt ?? { key: crypto.randomUUID(), address: addressId }; setAttempt(next); checkout.mutate(next); }}>{checkout.isPending ? "Đang đặt hàng…" : attempt ? "Thử lại lần đặt hàng này" : "Đặt hàng COD"}</Button>{checkout.error && <Notice error>{checkout.error.message}. Bạn có thể thử lại cùng lần đặt hàng.</Notice>}</aside></div>}</Page>;
}
